---
title: "data cleaning for overview"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(here)
```

```{r}
  scotland_health_survey <- read_csv(here("../data/raw_data/scotland_health_survey.csv")) %>%
  clean_names()
```

```{r}
scotland_health_survey_clean <- scotland_health_survey %>% 
  filter(scottish_health_survey_indicator %in% c("Any cardiovascular condition: Has a cardiovascular condition", "Any cardiovascular condition: No cardiovascular condition", "Life satisfaction: Above the mode (9 to 10-Extremely satisfied)", "Life satisfaction: Below the mode (0-Extremely dissatisfied to 7)", "Life satisfaction: Mode (8)", "Obesity: Not obese", "Obesity: Obese", "Overweight: Not overweight or obese", "Overweight: Overweight (including obese)", "Overweight: Overweight (including obese)", "Summary activity levels: Low activity", "Summary activity levels: Meets recommendations", "Summary activity levels: Some activity", "Summary activity levels: Very low activity"),
         measurement == "Percent")
```

```{r}
write_csv(scotland_health_survey_clean, "../data/clean_data/scotland_health_survey_clean.csv")
```


```{r}
greenspace <- read_csv(here("data/raw_data/greenspace.csv")) %>%
  clean_names() %>%
  filter(measurement == "Percent") %>%
  rename("value_percent" = "value", 
         "area_code" = "feature_code") %>%
  select(-"measurement", -"units")
  
```


```{r}
healthy_life_expectancy <- read_csv(here("data/raw_data/healthy_life_expectancy.csv")) %>%
  clean_names() %>%
  filter(measurement == "Count",
         date_code == "2016-2018") %>%
  rename("years_to_live" = "value") %>%
  select(-"measurement", -"units", -"feature_code")
  
```


```{r}
life_expectancy <- read_csv(here("data/raw_data/life_expectancy.csv")) %>%
  clean_names() %>%
  filter(measurement == "Count") %>%
  rename("years_to_live" = "value") %>%
  select(-"measurement", -"units", - "feature_code")
  
```


```{r}
council_names <- read_csv(here("data/clean_data/council_area_names.csv"))

   greenspace <- council_names %>% 
  select(area_code, ca_name) %>% 
  distinct() %>% 
  right_join(greenspace, by = "area_code")
```

```{r}
write_csv(life_expectancy, "../Desktop/codeclan/health_project/health_app/data/clean_data/life_expectancy.csv")
write_csv(healthy_life_expectancy, "../Desktop/codeclan/health_project/health_app/data/clean_data/healthy_life_expectancy.csv")
```


# reading in area code and name detail
```{r}
 area_names <- read_csv("../data/clean_data/council codes.csv") %>% 
    clean_names() %>% 
    rename(area_code = ca)
```


```{r}
council_codes <- area_names %>%
  select(area_code, hb_name)

health_board_codes <- area_names %>% 
  select(hb, hb_name) %>% 
  rename(area_code = hb)

health_board_names <- bind_rows(council_codes, health_board_codes) %>% 
  distinct()

```

```{r}
write_csv(health_board_names, "../data/clean_data/health_board_names.csv")
```



```{r}
scotland_health_survey_local <- read_csv(here("data/raw_data/scotland health survey local level.csv")) %>% 
  clean_names()
```



```{r}

scotland_health_survey_local <- scotland_health_survey_local %>% 
  rename(area_code = feature_code)

health_survey_local_clean <- health_board_names %>% 
  select(area_code, hb_name) %>% 
  distinct() %>% 
  right_join(scotland_health_survey_local, by = "area_code")

health_survey_local_clean %>% 
  filter(is.na(hb_name)) %>% 
  distinct(area_code)
```

